import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url),{JSDOM}=require('jsdom');
const html=await fs.readFile(new URL('../marketplace-mall.html',import.meta.url),'utf8');
const source=(await fs.readFile(new URL('../marketplace-mall.mjs',import.meta.url),'utf8')).replace("import Hls from './vendor/hls.light.mjs';",'const Hls={isSupported:()=>false};');
const listing={id:'a'.repeat(36),version:4,title:'Oak dining table',category:'home-goods',condition:'Good',city:'Baltimore',state:'MD',price:120,status:'LIVE',description:'Solid oak table with a scratch on the top.',fulfillment:'Local pickup.',photos:[],publishedAt:'2026-09-09',updatedAt:'2026-09-09'};
async function flush(){for(let n=0;n<8;n++)await new Promise(r=>setTimeout(r,0));}
async function app({hash='#browse',embedded=false,handler,query=''}={}){
    const dom=new JSDOM(html,{url:`https://easylotstoragesolutions.github.io/lighthouse-public-ui/marketplace-mall.html?${embedded?'embedded=1&':''}${query}${hash}`,runScripts:'outside-only',pretendToBeVisual:true});
    const w=dom.window,calls=[];w.structuredClone=structuredClone;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};
    const backend=async(action,input)=>{calls.push({action,input});if(handler)return handler(action,input);if(action==='session')return {signedIn:false};if(action==='browse')return {items:[listing],nextCursor:null};if(action==='detail')return {listing,store:null};if(action==='stores')return {items:[],nextCursor:null};throw new Error('Unexpected '+action);};
    if(embedded){const parent={postMessage:async request=>{try{const result=await backend(request.action,request.input);w.dispatchEvent(new w.MessageEvent('message',{source:parent,origin:'https://www.easylotstoragesolutions.com',data:{type:'mall:reply',requestId:request.requestId,result}}));}catch(error){w.dispatchEvent(new w.MessageEvent('message',{source:parent,origin:'https://www.easylotstoragesolutions.com',data:{type:'mall:reply',requestId:request.requestId,error:error.message}}));}}};Object.defineProperty(w,'parent',{value:parent});}
    w.fetch=async url=>{const p=new URL(url).searchParams;return {ok:true,json:()=>backend(p.get('action'),Object.fromEntries(p))};};
    await w.eval(`(async()=>{${source}\n})()`);await flush();
    return {w,dom,calls,close:()=>w.close(),async click(selector){const el=w.document.querySelector(selector);assert.ok(el,'Missing '+selector);el.click();await flush();},async submit(selector){w.document.querySelector(selector).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await flush();}};
}
test('browsing is public and returning from a listing preserves filters',async()=>{const a=await app({hash:'#browse?q=oak&location=Baltimore'});try{assert.match(a.w.document.body.textContent,/Oak dining table/);assert.equal(a.calls.some(c=>c.action==='login'),false);await a.click('a.title');assert.match(a.w.document.body.textContent,/Local pickup/);await a.click('#content > a');assert.equal(a.w.document.querySelector('[name=q]').value,'oak');assert.equal(a.w.document.querySelector('[name=location]').value,'Baltimore');}finally{a.close();}});
test('a zero-dollar listing is displayed as Free',async()=>{const a=await app({handler:async action=>action==='browse'?{items:[{...listing,price:0}],nextCursor:null}:{signedIn:false}});try{assert.equal(a.w.document.querySelector('.price').textContent,'Free');}finally{a.close();}});
test('loading errors have a working retry and Home escape',async()=>{let fail=true;const a=await app({handler:async action=>{if(action==='browse'){if(fail)throw new Error('Temporary outage');return {items:[listing],nextCursor:null};}return {signedIn:false};}});try{assert.match(a.w.document.body.textContent,/Temporary outage/);assert.ok(a.w.document.querySelector('[data-home]'));fail=false;await a.click('[data-action=refresh]');assert.match(a.w.document.body.textContent,/Oak dining table/);}finally{a.close();}});
test('sign-in continuation saves once and never starts a redirect loop',async()=>{const a=await app({embedded:true,hash:'#listing?id='+listing.id,query:'screen=listing&id='+listing.id+'&action=save',handler:async action=>{if(action==='session')return {signedIn:false};if(action==='detail')return {listing,store:null};if(action==='login')return {signedIn:true,id:'customer',name:'Customer'};if(action==='toggle')return {saved:true};throw new Error(action);}});try{assert.equal(a.calls.filter(c=>c.action==='login').length,1);assert.equal(a.calls.filter(c=>c.action==='toggle').length,1);assert.equal(a.w.location.hash,'#listing?id='+listing.id);}finally{a.close();}});
test('cancelled sign-in leaves a retry button and does not auto-prompt again',async()=>{const a=await app({embedded:true,hash:'#listing?id='+listing.id,query:'screen=listing&id='+listing.id+'&action=save',handler:async action=>{if(action==='session')return {signedIn:false};if(action==='detail')return {listing,store:null};if(action==='login')throw new Error('Sign-in cancelled');throw new Error(action);}});try{assert.equal(a.calls.filter(c=>c.action==='login').length,1);assert.ok(a.w.document.querySelector('[data-action=resume]'));await flush();assert.equal(a.calls.filter(c=>c.action==='login').length,1);}finally{a.close();}});
test('seller resumes the existing draft key instead of creating another listing',async()=>{const r={id:listing.id,kind:'listing',ownerId:'customer',version:2,data:{...listing,status:'DRAFT',draftKey:'original-draft-key',photos:[],vehicle:{}}};const a=await app({embedded:true,hash:'#seller',handler:async(action,input)=>{if(action==='session')return {signedIn:true,id:'customer',name:'Customer'};if(action==='workspace')return {items:input.kind==='listing'?[r]:[],nextCursor:null};if(action==='draft')return {...r,version:3,data:input.listing};throw new Error(action);}});try{await a.click('[data-action=edit-draft]');a.w.document.querySelector('[name=title]').value='Updated oak dining table';await a.click('[data-action=draft-save]');const write=a.calls.find(c=>c.action==='draft');assert.equal(write.input.draftKey,'original-draft-key');assert.equal(write.input.version,2);assert.equal(write.input.listing.title,'Updated oak dining table');}finally{a.close();}});
test('failed message send retains text and the same retry key',async()=>{let attempt=0;const thread={id:'thread-1',data:{title:'Oak table',buyerId:'customer'}};const a=await app({embedded:true,hash:'#messages?id=thread-1',handler:async(action,input)=>{if(action==='session')return {signedIn:true,id:'customer',name:'Customer'};if(action==='messages')return {items:[],nextCursor:null,thread,listing};if(action==='send'){attempt++;if(attempt===1)throw new Error('Temporary failure');return {id:'message-1'};}throw new Error(action);}});try{a.w.document.querySelector('[name=body]').value='Can we meet Saturday?';await a.submit('#message-form');assert.equal(a.w.document.querySelector('[name=body]').value,'Can we meet Saturday?');await a.submit('#message-form');const writes=a.calls.filter(c=>c.action==='send');assert.equal(writes[0].input.messageKey,writes[1].input.messageKey);assert.equal(a.w.document.querySelector('[name=body]').value,'');}finally{a.close();}});
test('store directory follows every page rather than hiding additional stores',async()=>{const a=await app({hash:'#stores',handler:async(action,input)=>{if(action==='stores')return input.cursor?{items:[{id:'two',name:'Second store'}],nextCursor:null}:{items:[{id:'one',name:'First store'}],nextCursor:'50'};return {signedIn:false};}});try{assert.match(a.w.document.body.textContent,/First store/);assert.match(a.w.document.body.textContent,/Second store/);assert.equal(a.calls.filter(c=>c.action==='stores').length,2);}finally{a.close();}});
